#!/usr/bin/env bash
# display information about subdomains from my domain

display_info () {
    dns_info=$(dig +short "$2"."$1" | awk '/ANSWER SECTION:/ {getline; print}')
    echo "$2" "$dns_info" | awk '{print "The subdomain " $1 " is a " $2 " and points to " $3 ""}'
}

for subdomain in "www" "lb-01" "web-01" "web-02"
do
    if [ -z "$2" ] || [ "$2" == "$subdomain" ];
    then
	display_info "$1" "$subdomain"
    fi
done
