#!/usr/bin/env bash
# Configure your Nginx server so that
# /redirect_me is redirecting to another page.
apt-get update
apt-get -y install nginx
ufw allow 'Nginx HTTP'

echo "Hello World!" | sudo tee /var/www/html/index.html

redirection_rule="location /redirect_me {
    return 301 https://www.youtube.com/watch?v=mLW35YMzELE;

}"

sudo sed -i "s/server_name _;/$redirection_rule/" /etc/nginx/sites-enabled/default

sudo service nginx restart
