#!/usr/bin/env bash
# Configure your Nginx server so that
# /redirect_me is redirecting to another page.
sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
echo "Hello World!" | sudo tee /var/www/html/index.html

sudo mkdir -p /var/www/redirect_me
echo "Redircting..." | sudo tee /var/www/redirect_me/index.html

sudo sed -i '/server_name _;/i \\tlocation /redirect_me {\n\t\treturn 301 https://youtube.com/watch?v=mLW35YMzELE;\n\t}' /etc/nginx/sites-available/default

sudo service nginx restart
