#!/usr/bin/env bash
# Configure your Nginx server to have a custom 404 page that contains the string Ceci n'est pas une page.
apt-get update
apt-get -y install nginx

echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html

sudo sed -i '/server_name _;/a \
    error_page 404 /404.html;\n\
    location = /404.html {\n\
        root /var/www/html;\n\
        internal;\n\
    }' /etc/nginx/sites-available/default

sudo service nginx restart
