#!/usr/bin/env bash
# Configure your Nginx server to have a custom 404 page that contains the string Ceci n'est pas une page.
apt-get update
apt-get -y install nginx

echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html

cat > /etc/nginx/sites-available/default <<EOF
server {
    listen 80 default_server;
    listen [::]:80 default_server;
    root /var/www/html;
    index index.html index.htm;

    error_page 404 /404.html;
    location = /404.html {
        internal;
    }
    location / {
        try_files \$uri \$uri/ =404;
    }

}
EOF

sudo service nginx restart