#!/usr/bin/env bash
# Configure Nginx so that its HTTP response contains a custom header (on web-01 and web-02)
sudo apt-get update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'

hostname=$(hostname)

sudo sed -i '/server_name _;/a \        add_header X-Served-By $hostname;' /etc/nginx/sites-available/default

sudo service nginx restart
