#!/usr/bin/env bash
# Configure Nginx so that its HTTP response contains a custom header (on web-01 and web-02)
sudo apt-get update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'

echo "Hello World!" | sudo tee /var/www/html/index.html
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html

sudo sed -i '/server_name _;/a \
    \tlocation /redirect_me {\n\
    \t\treturn 301 https://youtube.com/watch?v=mLW35YMzELE;\n\
    \t}' /etc/nginx/sites-available/default

sudo sed -i '/server_name _;/a \
    \terror_page 404 /404.html;\n\
    \tlocation = /404.html {\n\
    \t\troot /var/www/html;\n\
    \t\tinternal;\n\
    }' /etc/nginx/sites-available/default

sudo sed -i '/include \/etc\/nginx\/sites-enabled\/\*;/a \
    add_header X-Served-By "$HOSTNAME";' /etc/nginx/nginx.conf

sudo service nginx restart
