#!/usr/bin/env bash
# a Bash script that displays the PID, along with the process name, of processes whose name contain the word bash.
pids=$(pgrep -f bash)

for pid in $pids; do
    process_name=$(ps -o comm= -p "$pid")
    echo "$pid $process_name"
done
