#!/usr/bin/env bash
# install the ufw firewall and setup a few rules on.

sudo apt-get update
sudo apt-get install -y ufw

sudo ufw default deny incoming
sudo ufw default allow outgoing

sudo ufw allow 22/tcp
sudo ufw allow 443/tcp
sudo ufw allow 80/tcp

sudo ufw enable
sudo ufw status

sudo apt-get install -y iptables-persistent
sudo iptables -t nat -A PREROUTING -p tcp --dport 8080 -j REDIRECT --to-port 80
sudo netfilter-persistent save
