#!/usr/bin/env bash
#configure Nginx to serve your page from the route /airbnb-onepage/

server {
    listen      80 default_server;
    listen      [::]:80 default_server ipv6only=on;

    server_name 54.234.80.45;

    add_header  X-Served-By 522407-web-01;

    location = /airbnb-onepage/ {
        proxy_pass http://127.0.0.1:5000/airbnb-onepage/;
    }

    error_page 404 /404.html;
    location /404 {
        root /var/www/html;
        internal;
    }

}